version: 0.0
os: linux
files:
  - source: scripts/index.html
    destination: /usr/share/httpd/noindex
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root  
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
